# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 815ea4964799b5a9758b00b6ccf890a445c6a60b751533792310ec708ebcad35e1227481c46c4c443f4995b304a453d0a50a66389fbaad360fd44b37022b6116

test:
  secret_key_base: 999bbf07fb224cb74aeb03e20b043425aced8dda0500e7c19908c9451961ac85c837c9f7606511e19f56b4aa42ec2311c2e28c60cd508f7315eb7bd5b38d2860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
